/* Web Font Loader v1.5.2 - (c) Adobe Systems, Google. License: Apache 2.0 */
;(function(window,document,undefined){var j=null,k=!1;function m(a){return function(){return this[a]}}var n=this;function p(a,b){var c=a.split("."),d=n;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&void 0!==b?d[e]=b:d=d[e]?d[e]:d[e]={}}function aa(a,b,c){return a.call.apply(a.bind,arguments)}
function ba(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function q(a,b,c){q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?aa:ba;return q.apply(j,arguments)}var r=Date.now||function(){return+new Date};function s(a,b){this.z=a;this.fa=b||a;this.w=this.fa.document}s.prototype.createElement=function(a,b,c){a=this.w.createElement(a);if(b)for(var d in b)b.hasOwnProperty(d)&&("style"==d?a.style.cssText=b[d]:a.setAttribute(d,b[d]));c&&a.appendChild(this.w.createTextNode(c));return a};function t(a,b,c){a=a.w.getElementsByTagName(b)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(c,a.lastChild)}
function u(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return;c.push(b);a.className=c.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function v(a,b){for(var c=a.className.split(/\s+/),d=[],e=0,h=c.length;e<h;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function w(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return!0;return k}
function ca(a,b){var c=a.createElement("link",{rel:"stylesheet",href:b}),d=k;c.onload=function(){d||(d=!0)};c.onerror=function(){d||(d=!0)};t(a,"head",c)};function x(a,b,c){this.N=a;this.D=b;this.la=c}p("webfont.BrowserInfo",x);x.prototype.$=m("N");x.prototype.hasWebFontSupport=x.prototype.$;x.prototype.aa=m("D");x.prototype.hasWebKitFallbackBug=x.prototype.aa;x.prototype.ba=m("la");x.prototype.hasWebKitMetricsBug=x.prototype.ba;function y(a,b,c,d){this.b=a!=j?a:j;this.i=b!=j?b:j;this.L=c!=j?c:j;this.c=d!=j?d:j}var da=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;y.prototype.toString=function(){return[this.b,this.i||"",this.L||"",this.c||""].join("")};
function z(a){a=da.exec(a);var b=j,c=j,d=j,e=j;a&&(a[1]!==j&&a[1]&&(b=parseInt(a[1],10)),a[2]!==j&&a[2]&&(c=parseInt(a[2],10)),a[3]!==j&&a[3]&&(d=parseInt(a[3],10)),a[4]!==j&&a[4]&&(e=/^[0-9]+$/.test(a[4])?parseInt(a[4],10):a[4]));return new y(b,c,d,e)};function A(a,b,c,d,e,h,f,g,l,C,ea){this.r=a;this.ra=b;this.ka=c;this.Q=d;this.pa=e;this.P=h;this.ha=f;this.qa=g;this.ga=l;this.O=C;this.h=ea}p("webfont.UserAgent",A);A.prototype.getName=m("r");A.prototype.getName=A.prototype.getName;A.prototype.Z=m("ka");A.prototype.getVersion=A.prototype.Z;A.prototype.V=m("Q");A.prototype.getEngine=A.prototype.V;A.prototype.W=m("P");A.prototype.getEngineVersion=A.prototype.W;A.prototype.X=m("ha");A.prototype.getPlatform=A.prototype.X;A.prototype.Y=m("ga");
A.prototype.getPlatformVersion=A.prototype.Y;A.prototype.U=m("O");A.prototype.getDocumentMode=A.prototype.U;A.prototype.T=m("h");A.prototype.getBrowserInfo=A.prototype.T;function B(a,b){this.a=a;this.q=b}var fa=new A("Unknown",new y,"Unknown","Unknown",new y,"Unknown","Unknown",new y,"Unknown",void 0,new x(k,k,k));
B.prototype.parse=function(){var a;if(-1!=this.a.indexOf("MSIE")||-1!=this.a.indexOf("Trident/")){a=D(this);var b=E(this),c=z(b),d=j,e=j,h=j,f=j,g=F(this.a,/Trident\/([\d\w\.]+)/,1),l=G(this.q),d=-1!=this.a.indexOf("MSIE")?F(this.a,/MSIE ([\d\w\.]+)/,1):F(this.a,/rv:([\d\w\.]+)/,1),e=z(d);""!=g?(h="Trident",f=z(g)):(h="Unknown",f=new y,g="Unknown");a=new A("MSIE",e,d,h,f,g,a,c,b,l,new x("Windows"==a&&6<=e.b||"Windows Phone"==a&&8<=c.b,k,k))}else if(-1!=this.a.indexOf("Opera"))a:if(a="Unknown",b=F(this.a,
/Presto\/([\d\w\.]+)/,1),c=z(b),d=E(this),e=z(d),h=G(this.q),c.b!==j?a="Presto":(-1!=this.a.indexOf("Gecko")&&(a="Gecko"),b=F(this.a,/rv:([^\)]+)/,1),c=z(b)),-1!=this.a.indexOf("Opera Mini/"))f=F(this.a,/Opera Mini\/([\d\.]+)/,1),g=z(f),a=new A("OperaMini",g,f,a,c,b,D(this),e,d,h,new x(k,k,k));else{if(-1!=this.a.indexOf("Version/")&&(f=F(this.a,/Version\/([\d\.]+)/,1),g=z(f),g.b!==j)){a=new A("Opera",g,f,a,c,b,D(this),e,d,h,new x(10<=g.b,k,k));break a}f=F(this.a,/Opera[\/ ]([\d\.]+)/,1);g=z(f);a=
g.b!==j?new A("Opera",g,f,a,c,b,D(this),e,d,h,new x(10<=g.b,k,k)):new A("Opera",new y,"Unknown",a,c,b,D(this),e,d,h,new x(k,k,k))}else/OPR\/[\d.]+/.test(this.a)?a=H(this):/AppleWeb(K|k)it/.test(this.a)?a=H(this):-1!=this.a.indexOf("Gecko")?(a="Unknown",b=new y,c="Unknown",d=E(this),e=z(d),h=k,-1!=this.a.indexOf("Firefox")?(a="Firefox",c=F(this.a,/Firefox\/([\d\w\.]+)/,1),b=z(c),h=3<=b.b&&5<=b.i):-1!=this.a.indexOf("Mozilla")&&(a="Mozilla"),f=F(this.a,/rv:([^\)]+)/,1),g=z(f),h||(h=1<g.b||1==g.b&&9<
g.i||1==g.b&&9==g.i&&2<=g.L||f.match(/1\.9\.1b[123]/)!=j||f.match(/1\.9\.1\.[\d\.]+/)!=j),a=new A(a,b,c,"Gecko",g,f,D(this),e,d,G(this.q),new x(h,k,k))):a=fa;return a};function D(a){var b=F(a.a,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=F(a.a,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}
function E(a){var b=F(a.a,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b||(b=F(a.a,/Windows Phone( OS)? ([^;)]+)/,2))||(b=F(a.a,/(iPhone )?OS ([\d_]+)/,2)))return b;if(b=F(a.a,/(?:Linux|CrOS) ([^;)]+)/,1))for(var b=b.split(/\s/),c=0;c<b.length;c+=1)if(/^[\d\._]+$/.test(b[c]))return b[c];return(a=F(a.a,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function H(a){var b=D(a),c=E(a),d=z(c),e=F(a.a,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1),h=z(e),f="Unknown",g=new y,l="Unknown",C=k;/OPR\/[\d.]+/.test(a.a)?f="Opera":-1!=a.a.indexOf("Chrome")||-1!=a.a.indexOf("CrMo")||-1!=a.a.indexOf("CriOS")?f="Chrome":/Silk\/\d/.test(a.a)?f="Silk":"BlackBerry"==b||"Android"==b?f="BuiltinBrowser":-1!=a.a.indexOf("PhantomJS")?f="PhantomJS":-1!=a.a.indexOf("Safari")?f="Safari":-1!=a.a.indexOf("AdobeAIR")&&(f="AdobeAIR");"BuiltinBrowser"==f?l="Unknown":"Silk"==f?l=F(a.a,
/Silk\/([\d\._]+)/,1):"Chrome"==f?l=F(a.a,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.a.indexOf("Version/")?l=F(a.a,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==f?l=F(a.a,/AdobeAIR\/([\d\.]+)/,1):"Opera"==f?l=F(a.a,/OPR\/([\d.]+)/,1):"PhantomJS"==f&&(l=F(a.a,/PhantomJS\/([\d.]+)/,1));g=z(l);C="AdobeAIR"==f?2<g.b||2==g.b&&5<=g.i:"BlackBerry"==b?10<=d.b:"Android"==b?2<d.b||2==d.b&&1<d.i:526<=h.b||525<=h.b&&13<=h.i;return new A(f,g,l,"AppleWebKit",h,e,b,d,c,G(a.q),new x(C,536>h.b||536==h.b&&11>h.i,"iPhone"==
b||"iPad"==b||"iPod"==b||"Macintosh"==b))}function F(a,b,c){return(a=a.match(b))&&a[c]?a[c]:""}function G(a){if(a.documentMode)return a.documentMode};function I(a){this.ea=a||"-"}I.prototype.c=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.ea)};function J(a,b){this.r=a;this.F=4;this.s="n";var c=(b||"n4").match(/^([nio])([1-9])$/i);c&&(this.s=c[1],this.F=parseInt(c[2],10))}J.prototype.getName=m("r");function K(a){return a.s+a.F};function ga(a,b,c){this.d=a;this.f=b;this.t=c;this.g="wf";this.e=new I("-")}function L(a){v(a.f,a.e.c(a.g,"loading"));w(a.f,a.e.c(a.g,"active"))||u(a.f,a.e.c(a.g,"inactive"));M(a,"inactive")}function M(a,b,c){if(a.t[b])if(c)a.t[b](c.getName(),K(c));else a.t[b]()};function ha(){this.K={}};function N(a,b){this.d=a;this.o=b;this.k=this.d.createElement("span",{"aria-hidden":"true"},this.o)}
function O(a,b){for(var c=[],d=b.r.split(/,\s*/),e=0;e<d.length;e++){var h=d[e].replace(/['"]/g,"");-1==h.indexOf(" ")?c.push(h):c.push("'"+h+"'")}c="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+c.join(",")+";";d="normal";e=b.F+"00";"o"===b.s?d="oblique":"i"===b.s&&(d="italic");a.k.style.cssText=c+("font-style:"+d+";font-weight:"+e+";")}function P(a){t(a.d,"body",a.k)}
N.prototype.remove=function(){var a=this.k;a.parentNode&&a.parentNode.removeChild(a)};function Q(a,b,c,d,e,h,f,g){this.G=a;this.ca=b;this.d=c;this.j=d;this.o=g||"BESbswy";this.h=e;this.p={};this.C=h||5E3;this.J=f||j;this.n=this.m=j;a=new N(this.d,this.o);P(a);for(var l in R)R.hasOwnProperty(l)&&(O(a,new J(R[l],K(this.j))),this.p[R[l]]=a.k.offsetWidth);a.remove()}var R={oa:"serif",na:"sans-serif",ma:"monospace"};
Q.prototype.start=function(){this.m=new N(this.d,this.o);P(this.m);this.n=new N(this.d,this.o);P(this.n);this.ia=r();O(this.m,new J(this.j.getName()+",serif",K(this.j)));O(this.n,new J(this.j.getName()+",sans-serif",K(this.j)));S(this)};function T(a,b,c){for(var d in R)if(R.hasOwnProperty(d)&&b===a.p[R[d]]&&c===a.p[R[d]])return!0;return k}
function S(a){var b=a.m.k.offsetWidth,c=a.n.k.offsetWidth;b===a.p.serif&&c===a.p["sans-serif"]||a.h.D&&T(a,b,c)?r()-a.ia>=a.C?a.h.D&&T(a,b,c)&&(a.J===j||a.J.hasOwnProperty(a.j.getName()))?U(a,a.G):U(a,a.ca):setTimeout(q(function(){S(this)},a),25):U(a,a.G)}function U(a,b){a.m.remove();a.n.remove();b(a.j)};function V(a,b,c,d){this.d=b;this.l=c;this.v=0;this.M=this.I=k;this.C=d;this.h=a.h}function W(a,b,c,d,e){if(0===b.length&&e)L(a.l);else{a.v+=b.length;e&&(a.I=e);for(e=0;e<b.length;e++){var h=b[e],f=c[h.getName()],g=a.l,l=h;u(g.f,g.e.c(g.g,l.getName(),K(l).toString(),"loading"));M(g,"fontloading",l);(new Q(q(a.R,a),q(a.S,a),a.d,h,a.h,a.C,d,f)).start()}}}
V.prototype.R=function(a){var b=this.l;v(b.f,b.e.c(b.g,a.getName(),K(a).toString(),"loading"));v(b.f,b.e.c(b.g,a.getName(),K(a).toString(),"inactive"));u(b.f,b.e.c(b.g,a.getName(),K(a).toString(),"active"));M(b,"fontactive",a);this.M=!0;X(this)};V.prototype.S=function(a){var b=this.l;v(b.f,b.e.c(b.g,a.getName(),K(a).toString(),"loading"));w(b.f,b.e.c(b.g,a.getName(),K(a).toString(),"active"))||u(b.f,b.e.c(b.g,a.getName(),K(a).toString(),"inactive"));M(b,"fontinactive",a);X(this)};
function X(a){0==--a.v&&a.I&&(a.M?(a=a.l,v(a.f,a.e.c(a.g,"loading")),v(a.f,a.e.c(a.g,"inactive")),u(a.f,a.e.c(a.g,"active")),M(a,"active")):L(a.l))};function Y(a){this.z=a;this.H=new ha;this.ja=new B(a.navigator.userAgent,a.document);this.a=this.ja.parse();this.A=this.B=0}
Y.prototype.load=function(a){var b=a.context||this.z;this.d=new s(this.z,b);var b=new ga(this.d,b.document.documentElement,a),c=[],d=a.timeout;u(b.f,b.e.c(b.g,"loading"));M(b,"loading");var c=this.H,e=this.d,h=[],f;for(f in a)if(a.hasOwnProperty(f)){var g=c.K[f];g&&h.push(g(a[f],e))}c=h;this.A=this.B=c.length;a=new V(this.a,this.d,b,d);f=0;for(d=c.length;f<d;f++)this.da.call(this,c[f],b,a,this.a.h.N)};
Y.prototype.da=function(a,b,c,d){var e=this;d?a.load(function(a,b,d){var l=0==--e.B;setTimeout(function(){W(c,a,b||{},d||j,l)},0)}):(a=0==--this.B,this.A--,a&&0==this.A&&L(b),W(c,[],{},j,a))};function Z(a,b){this.d=a;this.u=b}Z.prototype.load=function(a){var b,c,d=this.u.urls||[],e=this.u.families||[],h=this.u.testStrings||{};b=0;for(c=d.length;b<c;b++)ca(this.d,d[b]);d=[];b=0;for(c=e.length;b<c;b++){var f=e[b].split(":");if(f[1])for(var g=f[1].split(","),l=0;l<g.length;l+=1)d.push(new J(f[0],g[l]));else d.push(new J(f[0]))}a(d,h)};var $=new Y(n);$.H.K.custom=function(a,b){return new Z(b,a)};n.WebFont||(n.WebFont={},n.WebFont.load=q($.load,$),n.WebFontConfig&&$.load(n.WebFontConfig));})(this,document);

